/**
 * Puzzle Journey art registry: art name -> bundled module id.
 *
 * Metro can only resolve literal `require` calls at build time, so this map
 * cannot be built by globbing at runtime. It mirrors `puzzle-assets.ts`.
 *
 * Requiring the @1x path is deliberate — Metro reads the sibling `@2x`/`@3x`
 * files and serves the right density per device.
 *
 * GENERATED by scripts/build-art.mjs's sibling generator, but committed and
 * safe to hand-edit. Adding an asset means dropping the SVG in
 * `assets/art-source/`, re-running `node scripts/build-art.mjs`, and adding
 * one line here.
 */

const ART = {
  album: require('../../assets/art/album.png'),
  back: require('../../assets/art/back.png'),
  'badge-1st': require('../../assets/art/badge-1st.png'),
  'badge-2nd': require('../../assets/art/badge-2nd.png'),
  'badge-3rd': require('../../assets/art/badge-3rd.png'),
  bars: require('../../assets/art/bars.png'),
  bear: require('../../assets/art/bear.png'),
  'bear-excited': require('../../assets/art/bear-excited.png'),
  bulb: require('../../assets/art/bulb.png'),
  calendar: require('../../assets/art/calendar.png'),
  car: require('../../assets/art/car.png'),
  castle: require('../../assets/art/castle.png'),
  category: require('../../assets/art/category.png'),
  'change-avatar': require('../../assets/art/change-avatar.png'),
  chest: require('../../assets/art/chest.png'),
  'chest-open': require('../../assets/art/chest-open.png'),
  clock: require('../../assets/art/clock.png'),
  coin: require('../../assets/art/coin.png'),
  'coin-check': require('../../assets/art/coin-check.png'),
  'coin-chest-10000': require('../../assets/art/coin-chest-10000.png'),
  'coin-chest-2200': require('../../assets/art/coin-chest-2200.png'),
  'coin-chest-5000': require('../../assets/art/coin-chest-5000.png'),
  'coins-1200': require('../../assets/art/coins-1200.png'),
  'coins-1500': require('../../assets/art/coins-1500.png'),
  'coins-500': require('../../assets/art/coins-500.png'),
  collection: require('../../assets/art/collection.png'),
  cup: require('../../assets/art/cup.png'),
  'cup-star': require('../../assets/art/cup-star.png'),
  edges: require('../../assets/art/edges.png'),
  eye: require('../../assets/art/eye.png'),
  gear: require('../../assets/art/gear.png'),
  gem: require('../../assets/art/gem.png'),
  'gems-chest': require('../../assets/art/gems-chest.png'),
  'gold-chest': require('../../assets/art/gold-chest.png'),
  'happy-duck': require('../../assets/art/happy-duck.png'),
  home: require('../../assets/art/home.png'),
  lock: require('../../assets/art/lock.png'),
  magnet: require('../../assets/art/magnet.png'),
  minus: require('../../assets/art/minus.png'),
  mountain: require('../../assets/art/mountain.png'),
  'my-trophies': require('../../assets/art/my-trophies.png'),
  pause: require('../../assets/art/pause.png'),
  pencil: require('../../assets/art/pencil.png'),
  'piece-area': require('../../assets/art/piece-area.png'),
  play: require('../../assets/art/play.png'),
  plus: require('../../assets/art/plus.png'),
  'plus-circle': require('../../assets/art/plus-circle.png'),
  'preview-image': require('../../assets/art/preview-image.png'),
  profile: require('../../assets/art/profile.png'),
  puppy: require('../../assets/art/puppy.png'),
  'puzzle-brown': require('../../assets/art/puzzle-brown.png'),
  'puzzle-green': require('../../assets/art/puzzle-green.png'),
  'puzzle-quad': require('../../assets/art/puzzle-quad.png'),
  'puzzle-yellow': require('../../assets/art/puzzle-yellow.png'),
  qr: require('../../assets/art/qr.png'),
  'quit-home': require('../../assets/art/quit-home.png'),
  restart: require('../../assets/art/restart.png'),
  resume: require('../../assets/art/resume.png'),
  'reveal-piece': require('../../assets/art/reveal-piece.png'),
  reward: require('../../assets/art/reward.png'),
  'reward-alt': require('../../assets/art/reward-alt.png'),
  'save-exit': require('../../assets/art/save-exit.png'),
  'shield-star': require('../../assets/art/shield-star.png'),
  shuffle: require('../../assets/art/shuffle.png'),
  star: require('../../assets/art/star.png'),
  'sticker-book': require('../../assets/art/sticker-book.png'),
  'watch-ad': require('../../assets/art/watch-ad.png'),
  'winking-duck': require('../../assets/art/winking-duck.png'),
  wordmark: require('../../assets/art/wordmark.png'),
} as const;

/** Every art name the app can draw. A typo is a type error, not a blank box. */
export type ArtName = keyof typeof ART;

export function getArtModule(name: ArtName): number {
  return ART[name];
}

/** For tests and tooling that need to walk the whole set. */
export const ART_NAMES = Object.keys(ART) as ArtName[];
